#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# OmniRoute — ONE-CLICK INSTALLER
# ═══════════════════════════════════════════════════════════════
# This script does EVERYTHING for a new user:
#   1. Checks Node.js / npm
#   2. Installs omniroute globally if missing
#   3. Creates ~/.omniroute/ and ~/.omniroute/.env (with encryption key)
#   4. Copies api-keys.env from template if missing
#   5. Registers no-auth providers
#   6. Registers API key providers (if api-keys.env has keys)
#   7. Builds all routing combos
#   8. Activates mega-free
#   9. Adds shell aliases for noise-free monitoring
#
# Run: ./scripts/install.sh

set +e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'
print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_error() { echo -e "${RED}✖ $1${NC}"; }
print_info() { echo -e "${CYAN}→ $1${NC}"; }
_print_header() {
    echo ""; echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE} $1${NC}"; echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"; echo ""
}

# Detect shell RC
SHELL_RC="$HOME/.zshrc"
[ -z "$ZSH_VERSION" ] && [ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"

_print_header "Step 1/9 — Check Node.js"
if command -v node >/dev/null 2>&1; then
    print_success "Node.js $(node -v)"
else
    print_error "Node.js is missing."
    echo "  macOS:   brew install node"
    echo "  Linux:   curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt install -y nodejs"
    echo "  Windows: https://nodejs.org/"
    exit 1
fi
print_success "npm $(npm -v)"

_print_header "Step 2/9 — Install omniroute"
if command -v omniroute >/dev/null 2>&1; then
    print_success "omniroute already installed"
else
    print_info "Installing omniroute globally (this may take 1-2 minutes)..."
    npm install -g omniroute
    if command -v omniroute >/dev/null 2>&1; then
        print_success "omniroute installed"
    else
        print_error "omniroute install failed. Try: sudo npm install -g omniroute"
        exit 1
    fi
fi

_print_header "Step 3/9 — Create ~/.omniroute directory"
mkdir -p "$HOME/.omniroute"
print_success "$HOME/.omniroute exists"

# Generate .env with encryption key (this fixes the "STORAGE_ENCRYPTION_KEY ignored" warning)
if [ ! -f "$HOME/.omniroute/.env" ] || ! grep -q "STORAGE_ENCRYPTION_KEY=" "$HOME/.omniroute/.env" 2>/dev/null; then
    print_info "Generating ~/.omniroute/.env with STORAGE_ENCRYPTION_KEY..."
    KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    cat > "$HOME/.omniroute/.env" <<EOF
# OmniRoute — auto-generated by omniroute-config/install.sh
# Required so the npm-installed package's default key is ignored.
STORAGE_ENCRYPTION_KEY=$KEY
EOF
    chmod 600 "$HOME/.omniroute/.env"
    print_success ".env created (chmod 600 — private)"
else
    print_success ".env already exists"
fi

_print_header "Step 4/9 — Set up api-keys.env"
if [ -f "$HOME/.omniroute/api-keys.env" ]; then
    print_success "api-keys.env already exists"
else
    if [ -f "configs/api-keys.env.example" ]; then
        cp "configs/api-keys.env.example" "$HOME/.omniroute/api-keys.env"
        chmod 600 "$HOME/.omniroute/api-keys.env"
        print_success "Created api-keys.env from template"
        print_warning "Edit with your keys: nano ~/.omniroute/api-keys.env"
    else
        print_warning "Template not found — you'll need to create ~/.omniroute/api-keys.env manually"
    fi
fi

_print_header "Step 5/9 — Register no-auth providers"
NOAUTH=(aihorde opencode huggingchat firecrawl searxng-search ollama-cloud zcode)
for p in "${NOAUTH[@]}"; do
    omniroute providers add "$p" --no-credential --yes >/dev/null 2>&1 \
        && print_success "$p" \
        || print_warning "$p (may already exist)"
done

_print_header "Step 6/9 — Register API key providers"
if [ -f "$HOME/.omniroute/api-keys.env" ]; then
    grep -q "=" "$HOME/.omniroute/api-keys.env" 2>/dev/null \
        && bash "$(dirname "$0")/add-keys.sh" \
        || print_warning "api-keys.env is empty — skip. Add keys then re-run: ./scripts/add-keys.sh"
else
    print_warning "Skipping — no api-keys.env"
fi

_print_header "Step 7/9 — Build routing combos"
bash "$(dirname "$0")/combo.sh"

_print_header "Step 8/9 — Activate mega-free"
omniroute combo switch mega-free >/dev/null 2>&1
print_success "mega-free is active"

_print_header "Step 9/9 — Shell aliases (noise-filtered OmniRoute commands)"
ALIASES=$(cat <<'EOF'

# ── OmniRoute noise-filtered aliases ───────────────────────────
alias or-combos="omniroute combo list 2>&1 | tail -n +5"
alias or-usage="omniroute usage analytics 2>&1 | tail -n +5"
alias or-util="omniroute usage utilization 2>&1 | tail -n +5"
alias or-logs="omniroute usage logs 2>&1 | tail -n +5"
alias or-quota="omniroute quota 2>&1 | tail -n +5"
alias or-telemetry="omniroute telemetry 2>&1 | tail -n +5"
alias or-cost="omniroute cost 2>&1 | tail -n +5"
alias or-status="omniroute providers status 2>&1 | tail -n +5"
alias or-metrics="omniroute providers metrics 2>&1 | tail -n +5"
alias or-serve="omniroute serve"
EOF
)
if grep -q "or-combos" "$SHELL_RC" 2>/dev/null; then
    print_success "Aliases already in $SHELL_RC"
else
    echo "$ALIASES" >> "$SHELL_RC"
    print_success "Aliases added to $SHELL_RC"
fi

_print_header "🎉 DONE — What to do next"
cat <<EOF
1.  Add your API keys:
      ${CYAN}nano ~/.omniroute/api-keys.env${NC}
    Then re-run:
      ${CYAN}./scripts/add-keys.sh${NC}

2.  Start the OmniRoute server (REQUIRED before Claude Code):
      ${CYAN}omniroute serve &${NC}
    (or run it in a dedicated terminal)

3.  Configure your coding tool to use OmniRoute:
      ${CYAN}export ANTHROPIC_BASE_URL=http://localhost:4000${NC}
      ${CYAN}export ANTHROPIC_API_KEY=omniroute${NC}
    Add these to ${SHELL_RC} to persist:
      ${CYAN}echo 'export ANTHROPIC_BASE_URL=http://localhost:4000' >> $SHELL_RC${NC}
      ${CYAN}echo 'export ANTHROPIC_API_KEY=omniroute' >> $SHELL_RC${NC}
      ${CYAN}source $SHELL_RC${NC}

4.  Verify:
      ${CYAN}omniroute providers list${NC}    # all keys registered
      ${CYAN}omniroute combo switch mega-free${NC}
      ${CYAN}or-combos${NC}                   # noise-free list

5.  Use Claude Code / Cursor / Codex — it now routes through free providers.

    Estimated monthly budget with full setup: 1.5B+ tokens.
EOF